import { useState } from 'react';
import { ArrowRight, Bank, CalendarBlank, CheckCircle, Clock, CreditCard, ListChecks, RocketLaunch, Repeat, HandPalm, Trophy, BookOpen, Target, Brain, UsersThree, InstagramLogo, EnvelopeSimple, Wallet, X, List, PlayCircle } from '@phosphor-icons/react';

const skills=[[CalendarBlank,'Weekly planning'],[RocketLaunch,'Starting tasks'],[HandPalm,'Asking for help'],[Repeat,'Recovering after setbacks'],[ListChecks,'The One-Page Week'],[Clock,'The 10-Minute Launch'],[Repeat,'The RESET Routine'],[BookOpen,'The 14-Day Playbook'],[Trophy,'Confidence in school & sports']];
const sessions=[['01',CalendarBlank,'Know Your Game','Build one home base for the week with the One-Page Week.'],['02',RocketLaunch,'Start Strong','Use the 10-Minute Launch to begin before you feel fully ready.'],['03',Repeat,'Reset Like an Athlete','Recover after a tough grade, missed deadline, or mistake.'],['04',HandPalm,'Run Your Own Playbook','Create a practical 14-day plan and ask for the right support.']];
const pillars=[['01',Target,'Clear','Make the goal, next step, and expectations easy to understand.'],['02',CheckCircle,'Correct','Adjust the plan with care when something is not working.'],['03',BookOpen,'Learn','Turn every experience into a lesson and a useful new skill.'],['04',UsersThree,'Encourage Accountability','Offer support while helping students take ownership of their choices.'],['05',CalendarBlank,'Remind','Use timely, respectful reminders that build consistency and independence.']];
const checkoutLinks={online:'https://book.stripe.com/eVqeVcbHq0qN1Z84Fv8N200',inPerson:'https://book.stripe.com/14A00iaDm8Xj6fo0pf8N201'};

export function App(){
 const[menuOpen,setMenuOpen]=useState(false);const[submitted,setSubmitted]=useState(false);
 const scrollTo=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenuOpen(false)};
 const submitInterest=e=>{e.preventDefault();const data=new FormData(e.currentTarget);const subject=encodeURIComponent('The GUS Experience interest list');const body=encodeURIComponent(`Parent or guardian: ${data.get('name')}\nEmail: ${data.get('email')}\nStudent grade: ${data.get('grade')}\nPreferred format: ${data.get('format')}\n\nPlease send me upcoming GUS Teen Success Sprint enrollment details.`);window.location.href=`mailto:gus@thegusexperience.org?subject=${subject}&body=${body}`;setSubmitted(true)};
 const requestPayment=method=>{const subject=encodeURIComponent(`The GUS Experience — ${method} monthly package request`);const body=encodeURIComponent(`Hello Coach Gus,\n\nI would like payment instructions for a GUS monthly coaching package using ${method}.\n\nPlease select one:\n[ ] Online monthly package (four one-hour sessions) — $300 per student\n[ ] In-person monthly package in New York or New Jersey (four one-hour sessions) — $425 per student\n[ ] Request a custom quote for another location\n\nParent or guardian name:\nBest phone number:\n\nThank you.`);window.location.href=`mailto:gus@thegusexperience.org?subject=${subject}&body=${body}`};
 return <div className="site-shell">
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="header"><div className="container nav-wrap">
   <button className="brand" onClick={()=>scrollTo('home')} aria-label="The GUS Experience home"><img src="/assets/gus-logo.png" alt="The GUS Experience mascot logo"/><span><b>THE GUS</b><small>EXPERIENCE</small></span></button>
   <nav className={menuOpen?'nav-links open':'nav-links'} aria-label="Primary navigation"><button onClick={()=>scrollTo('coaching')}>Coaching</button><button onClick={()=>scrollTo('sessions')}>How it works</button><button onClick={()=>scrollTo('for-who')}>Who it’s for</button><button onClick={()=>scrollTo('about')}>About Gus</button><button onClick={()=>scrollTo('payments')}>Payments</button><button onClick={()=>scrollTo('faq')}>FAQ</button></nav>
   <button className="nav-cta" onClick={()=>scrollTo('interest')}>Join the interest list <ArrowRight/></button><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle menu">{menuOpen?<X/>:<List/>}</button>
  </div></header>
  <main id="main">
   <section className="hero" id="home"><div className="hero-streak" aria-hidden="true"/><div className="container hero-grid">
    <div className="hero-copy"><p className="eyebrow">The GUS Teen Success Sprint</p><h1>Focus.<br/>Plan.<br/><em>Take the shot.</em></h1><p className="hero-lede">Four practical sessions for stronger organization, confidence, and performance in school and sports.</p><div className="hero-actions"><button className="button button-primary" onClick={()=>scrollTo('interest')}>Join the interest list <ArrowRight/></button><button className="button button-secondary" onClick={()=>scrollTo('sessions')}>See the four sessions <PlayCircle/></button></div></div>
    <div className="hero-art"><img src="/assets/coach-gus-final-gus-v2.png" alt="Anime illustration of Coach Gus wearing a GUS and The GUS Experience jacket, holding a book and basketball"/><div className="hero-ribbon"><span>Practical guidance.</span><strong>Real progress.</strong></div></div>
   </div></section>
   <section className="skills" id="coaching"><div className="container skills-grid"><div className="skills-intro"><h2>Coaching that builds the skills teens use at school and on the court.</h2><span className="scribble"/><p>Simple systems. Weekly practice. Real momentum—one week at a time.</p></div><div className="skill-list">{skills.map(([Icon,label])=><div className="skill" key={label}><Icon weight="duotone"/><span>{label}</span></div>)}</div></div></section>
   <section className="pillars" id="pillars"><div className="container"><p className="eyebrow centered">The GUS approach</p><h2 className="section-title">Five pillars that keep progress moving.</h2><div className="pillar-grid">{pillars.map(([number,Icon,title,text])=><article className="pillar" key={title}><span className="pillar-number">{number}</span><Icon weight="duotone"/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
   <section className="sessions" id="sessions"><div className="container"><p className="eyebrow centered">Four practical sessions</p><h2 className="section-title">Real skills. Real practice. Real results.</h2><div className="session-grid">{sessions.map(([number,Icon,title,text])=><article className="session" key={number}><span className="session-number">{number}</span><Icon weight="duotone"/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
   <section className="who" id="for-who"><div className="container who-grid"><div><p className="eyebrow light">Who it’s for</p><h2>Capable teens who need a clearer game plan—not another lecture.</h2></div><div className="who-points"><p><CheckCircle weight="fill"/> High-school students balancing school, sports, home, and energy.</p><p><CheckCircle weight="fill"/> Students who struggle to start, organize, recover, or ask for help.</p><p><CheckCircle weight="fill"/> Families who want students to own their plan with supportive accountability.</p></div></div></section>
   <section className="about" id="about"><div className="container about-grid"><div className="about-image"><img src="/assets/coach-gus-grand-canyon-portrait-v4.jpg" alt="Coach Gus smiling at the Grand Canyon"/></div><div className="about-copy"><p className="eyebrow">Meet Coach Gus</p><h2>Structure, empathy, and the energy of a great coach.</h2><p>Gus Kennedy is a physical-education teacher, student executive-function support teacher, happiness coach, and sports coach. He brings practical systems, deep listening, and a real understanding of teenagers into every session.</p><div className="about-badges"><span><UsersThree/>Teen-centered</span><span><Target/>Strengths-focused</span><span><Brain/>Practical tools</span></div></div></div></section>
   <section className="payments" id="payments"><div className="container"><div className="payment-heading"><div><p className="eyebrow light">Monthly coaching packages</p><h2>Four sessions. One clear plan.</h2><p>Choose a monthly package for one student. Each package includes four one-hour coaching sessions. Individual sessions are not offered separately.</p><div className="price-details"><span><strong>$300</strong> online monthly package</span><span><strong>$425</strong> in person in New York or New Jersey</span></div></div><div className="price-badge price-badge-plans"><span>Monthly</span><strong>$300</strong><small>online</small><i>or</i><strong>$425</strong><small>NY / NJ</small></div></div><div className="payment-grid"><article className="payment-card featured"><span className="payment-icon"><CreditCard weight="duotone"/></span><div><p className="payment-kicker">Recommended</p><h3>Secure Stripe checkout</h3><p>Choose a monthly package and pay securely by card or an eligible payment option. Klarna, Afterpay/Clearpay, Cash App Pay, Link, or a bank option may appear when eligible.</p></div><div className="checkout-options"><a className="button button-primary" href={checkoutLinks.online} target="_blank" rel="noreferrer">Pay $300 — Online <ArrowRight/></a><a className="button button-secondary" href={checkoutLinks.inPerson} target="_blank" rel="noreferrer">Pay $425 — NY / NJ</a></div></article><article className="payment-card"><span className="payment-icon"><Wallet weight="duotone"/></span><div><h3>PayPal or Venmo</h3><p>Request a PayPal payment link. Eligible U.S. customers may also be able to choose Venmo through PayPal.</p></div><button className="button button-secondary" onClick={()=>requestPayment('PayPal or Venmo')}>Request PayPal or Venmo</button></article><article className="payment-card"><span className="payment-icon"><Bank weight="duotone"/></span><div><h3>Zelle</h3><p>Zelle is available by request for families whose bank supports enrolled business payments.</p></div><button className="button button-secondary" onClick={()=>requestPayment('Zelle')}>Request Zelle instructions</button></article></div><div className="after-payment"><CheckCircle weight="fill"/><div><strong>After payment</strong><p>The parent or guardian receives a payment receipt, the GUS Parent Packet, and scheduling details by email. Before the package ends, we will email a reminder with the option to renew for another month. Packages do not renew automatically.</p></div></div><p className="payment-note">In-person coaching outside New York or New Jersey may be available by special arrangement and requires a custom travel quote. Payment information is handled securely by the selected provider—not stored on this website.</p></div></section>
   <section className="interest" id="interest"><div className="container interest-grid"><div className="interest-copy"><p className="eyebrow light">The next cohort</p><h2>You bring the drive.<br/><em>We bring the game plan.</em></h2><p>Join the interest list to hear about upcoming dates, format, and enrollment. No pressure—just the details you need.</p><small>Educational coaching and skill-building—not therapy, diagnosis, or medical treatment.</small></div><div className="form-card">{submitted?<div className="success-state" role="status"><CheckCircle weight="fill"/><h3>Your email is ready</h3><p>Send the message in your email app to join the list. Coach Gus will follow up with enrollment details.</p><button className="button button-secondary" onClick={()=>setSubmitted(false)}>Add another family</button></div>:<form onSubmit={submitInterest}><h3>Join the interest list</h3><label>Parent or guardian name<input required name="name" autoComplete="name"/></label><label>Email address<input required name="email" type="email" autoComplete="email"/></label><label>Student grade<select required name="grade" defaultValue=""><option value="" disabled>Select grade</option><option>9th grade</option><option>10th grade</option><option>11th grade</option><option>12th grade</option><option>First-year college</option></select></label><label>Preferred format<select name="format" defaultValue="either"><option value="either">Online or in person in New York or New Jersey</option><option value="online">Online</option><option value="new-york-new-jersey">In person in New York or New Jersey</option><option value="other-location">Another location — request a custom quote</option></select></label><button className="button button-primary" type="submit">Email my interest <ArrowRight/></button><p className="privacy-note">This opens your email app. Your information is sent only when you choose Send.</p></form>}</div></div></section>
   <section className="faq" id="faq"><div className="container"><p className="eyebrow centered">Questions</p><h2 className="section-title">What families ask</h2><div className="faq-grid"><details><summary>Is this therapy or tutoring?</summary><p>No. The Sprint is educational coaching and practical skill-building. It is not therapy, diagnosis, medical care, or subject tutoring.</p></details><details><summary>Will parents be involved?</summary><p>Parents receive brief progress updates after Sessions 2 and 4. Students still own their plan and practice independence.</p></details><details><summary>What happens after payment?</summary><p>The parent or guardian receives a payment receipt and the GUS Parent Packet by email. Coach Gus then follows up with scheduling and next-step details.</p></details><details><summary>Does the monthly package renew automatically?</summary><p>No. Before the four-session package ends, the parent or guardian receives an email reminder and may choose whether to purchase another month.</p></details><details><summary>What if my teenager is shy?</summary><p>Students are never forced to disclose personal information. Activities allow speaking, writing, and hands-on planning.</p></details><details><summary>Where are sessions held?</summary><p>Sessions may be online or in person in New York or New Jersey, depending on scheduling. Other locations may be available by special arrangement with a custom travel quote.</p></details></div></div></section>
  </main>
  <footer><div className="container footer-grid"><div className="footer-brand"><img src="/assets/gus-logo.png" alt=""/><div><b>The GUS Experience</b><small>Focus. Plan. Take the shot.</small></div></div><div className="footer-links"><button onClick={()=>scrollTo('sessions')}>Program</button><button onClick={()=>scrollTo('about')}>Coach Gus</button><button onClick={()=>scrollTo('payments')}>Payments</button><button onClick={()=>scrollTo('interest')}>Contact</button></div><div className="social"><a href="https://www.instagram.com/thegustexperience/" target="_blank" rel="noreferrer" aria-label="The GUS Experience on Instagram"><InstagramLogo/></a><a href="mailto:gus@thegusexperience.org" aria-label="Email Coach Gus"><EnvelopeSimple/></a></div></div><div className="container copyright"><span>© 2026 The GUS Experience. All rights reserved.</span><span className="site-domain">GusExperience.org</span><span>The GUS Experience is an educational brand of What-A-Rush Media LLC.</span></div></footer>
 </div>
}
